// Copyright (C) 2024 owoDra

#pragma once

#include "Type/OnlineServiceTypes.h"

#include "OnlinePrivilegeTypes.generated.h"

class ULocalUserAccountInfo;


////////////////////////////////////////////////////////////////////////
// Enums

/**
 * Enum specifying different privileges and capabilities available to a user
 */
UENUM(BlueprintType)
enum class ELocalUserPrivilege : uint8
{
	// Whether the user can play at all, online or offline
	CanPlay,

	// Whether the user can play in online modes
	CanPlayOnline,

	// Whether the user can use text chat
	CanCommunicateViaTextOnline,

	// Whether the user can use voice chat
	CanCommunicateViaVoiceOnline,

	// Whether the user can access content generated by other users
	CanUseUserGeneratedContent,

	// Whether the user can ever participate in cross-play
	CanUseCrossPlay,

	// Count of valid privilege
	Count	UMETA(Hidden),

	// Invalid privilege
	Invalid	UMETA(Hidden)
};


/**
 * Enum giving specific reasons why a user may or may not use a certain privilege
 */
UENUM(BlueprintType)
enum class ELocalUserPrivilegeResult : uint8
{
	// State is unknown and needs to be queried
	Unknown,

	// This privilege is fully available for use
	Available,

	// User has not fully logged in
	UserNotLoggedIn,

	// User does not own the game or content
	LicenseInvalid,

	// The game needs to be updated or patched before this will be available
	VersionOutdated,

	// No network connection, this may be resolved by reconnecting
	NetworkConnectionUnavailable,

	// Parental control failure
	AgeRestricted,

	// Account does not have a required subscription or account type
	AccountTypeRestricted,

	// Another account/user restriction such as being banned by the service
	AccountUseRestricted,

	// Other platform-specific failure
	PlatformFailure,
};


/**
 * Enum specifying the general availability of a feature or privilege, this combines information from multiple sources
 */
UENUM(BlueprintType)
enum class ELocalUserAvailability : uint8
{
	// State is completely unknown and needs to be queried
	Unknown,

	// This feature is fully available for use right now
	NowAvailable,

	// This might be available after the completion of normal login procedures
	PossiblyAvailable,

	// This feature is not available now because of something like network connectivity but may be available in the future
	CurrentlyUnavailable,

	// This feature will never be available for the rest of this session due to hard account or platform restrictions
	AlwaysUnavailable,

	// Invalid feature
	Invalid,
};


////////////////////////////////////////////////////////////////////////
// Delegates

/** 
 * Delegate when a privilege changes, this can be bound to see if online status/etc changes during gameplay 
 */
DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams(FLocalUserAvailabilityChangedDelegate
												, const ULocalUserAccountInfo*	, UserInfo
												, ELocalUserPrivilege			, Privilege
												, ELocalUserAvailability		, OldAvailability
												, ELocalUserAvailability		, NewAvailability);

/**
 * Delegate notifies that the save has been loaded
 */
DECLARE_DELEGATE_FiveParams(FLocalUserPrivilegeQueryDelegate
								, ULocalUserAccountInfo*				/* UserInfo */
								, EOnlineServiceContext					/* Context */
								, ELocalUserPrivilege					/* DesiredPrivilege */
								, ELocalUserPrivilegeResult				/* PrivilegeResult */
								, const TOptional<FOnlineErrorType>&	/* Error */);
