// Copyright (C) 2024 owoDra

#pragma once

#include "Type/OnlineServiceContextTypes.h"
#include "Type/OnlineServiceResultTypes.h"

#include "OnlinePrivilegeTypes.generated.h"

class ULocalPlayer;


////////////////////////////////////////////////////////////////////////
// Enums

/**
 * Enum specifying different privileges and capabilities available to a user
 */
UENUM(BlueprintType)
enum class EOnlinePrivilege : uint8
{
	// Whether the user can play at all, online or offline
	CanPlay,

	// Whether the user can play in online modes
	CanPlayOnline,

	// Whether the user can use text chat
	CanCommunicateViaTextOnline,

	// Whether the user can use voice chat
	CanCommunicateViaVoiceOnline,

	// Whether the user can access content generated by other users
	CanUseUserGeneratedContent,

	// Whether the user can ever participate in cross-play
	CanUseCrossPlay,

	// Count of valid privilege
	Count	UMETA(Hidden),

	// Invalid privilege
	Invalid	UMETA(Hidden)
};


/**
 * Enum giving specific reasons why a user may or may not use a certain privilege
 */
UENUM(BlueprintType)
enum class EOnlinePrivilegeResult : uint8
{
	// State is unknown and needs to be queried
	Unknown,

	// This privilege is fully available for use
	Available,

	// User has not fully logged in
	UserNotLoggedIn,

	// User does not own the game or content
	LicenseInvalid,

	// The game needs to be updated or patched before this will be available
	VersionOutdated,

	// No network connection, this may be resolved by reconnecting
	NetworkConnectionUnavailable,

	// Parental control failure
	AgeRestricted,

	// Account does not have a required subscription or account type
	AccountTypeRestricted,

	// Another account/user restriction such as being banned by the service
	AccountUseRestricted,

	// Other platform-specific failure
	PlatformFailure,
};


////////////////////////////////////////////////////////////////////////
// Delegates

/**
 * Delegate notifies that the save has been loaded
 */
DECLARE_DELEGATE_FiveParams(FOnlinePrivilegeQueryDelegate
								, const ULocalPlayer*		/* LocalPlayer */
								, EOnlineServiceContext		/* Context */
								, EOnlinePrivilege			/* DesiredPrivilege */
								, EOnlinePrivilegeResult	/* PrivilegeResult */
								, FOnlineServiceResult		/* ServiceResult */);
