// Copyright (C) 2024 owoDra

#pragma once

#include "Logging/LogMacros.h"

GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineAchievements, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineAuth, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineCommerce, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineConnectivity, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineLeaderboards, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineLobbies, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlinePresence, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlinePrivileges, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineSessions, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineSocial, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineStats, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineTitleFile, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineUserFile, Log, All);
GCONLINE_API DECLARE_LOG_CATEGORY_EXTERN(LogGameCore_OnlineUserInfo, Log, All);
